version: "3.9"

services:
  bot-app:
    container_name: wb-bot-app
    depends_on:
      -   bot-db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      context: .
      target: prod
    environment:
      DB_USERNAME: ${DB_USERNAME:?dbUserNameNorProvided}
      DB_PASSWORD: ${DB_PASSWORD:?dbPasswordNotProvided}
      DB_NAME: ${DB_NAME:?dbNameNotProvided}
      DB_HOST: bot-db
      DB_PORT: 5432
      APP_PORT: ${APP_PORT:?appPortNotProvided}
    restart: unless-stopped
  bot-db:
    container_name: wb-bot-db
    image: 'postgres:13.1-alpine'
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./.wb-bot-db:/var/lib/postgresql/data